using Microsoft.AspNetCore.Mvc;

namespace HowrsePrixCalculateWinner.Server.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class BonusCategoryController : ControllerBase
    {
        [HttpGet(Name = "GetBonusCategory")]
        public IEnumerable<CustomizationBonus> Get()
        {
            return new List<CustomizationBonus>
             {
                new CustomizationBonus { Name = "Medusan veri",
                                        Stamina = 3,
                                        Speed = 4,
                                        Dressage = 4,
                                        Gallop = 0,
                                        Trot = 0,
                                        Jumping = 0 },
                new CustomizationBonus { Name = "Perusmukautus*",
                                        Stamina = 11,
                                        Speed = 11,
                                        Dressage = 11,
                                        Gallop = 11,
                                        Trot = 11,
                                        Jumping = 11 },
                new CustomizationBonus { Name = "Vesielementti",
                                        Stamina = 14,
                                        Speed = 11,
                                        Dressage = 11,
                                        Gallop = 11,
                                        Trot = 11,
                                        Jumping = 11 },
                new CustomizationBonus { Name = "Tulielementti",
                                        Stamina = 11,
                                        Speed = 14,
                                        Dressage = 11,
                                        Gallop = 11,
                                        Trot = 11,
                                        Jumping = 11 },
                new CustomizationBonus { Name = "Maaelementti",
                                        Stamina = 11,
                                        Speed = 11,
                                        Dressage = 14,
                                        Gallop = 11,
                                        Trot = 11,
                                        Jumping = 11 },
                new CustomizationBonus { Name = "Ilmaelementti",
                                        Stamina = 11,
                                        Speed = 11,
                                        Dressage = 11,
                                        Gallop = 11,
                                        Trot = 11,
                                        Jumping = 14 },
                new CustomizationBonus { Name = "Metallielementti",
                                        Stamina = 14,
                                        Speed = 14,
                                        Dressage = 14,
                                        Gallop = 14,
                                        Trot = 14,
                                        Jumping = 14 },
                new CustomizationBonus { Name = "Ilmestyskirjan sinetti, Bellum",
                                        Stamina = 14,
                                        Speed = 14,
                                        Dressage = 14,
                                        Gallop = 14,
                                        Trot = 14,
                                        Jumping = 14 },
                new CustomizationBonus { Name = "Taikahattu, Keiju",
                                        Stamina = 14,
                                        Speed = 14,
                                        Dressage = 14,
                                        Gallop = 14,
                                        Trot = 14,
                                        Jumping = 14 },
                new CustomizationBonus { Name = "Hirviökirja, Aaveratsastaja",
                                        Stamina = 14,
                                        Speed = 14,
                                        Dressage = 14,
                                        Gallop = 14,
                                        Trot = 14,
                                        Jumping = 14 },
                new CustomizationBonus { Name = "Lumottu kurpitsa, Lepakko",
                                        Stamina = 14,
                                        Speed = 14,
                                        Dressage = 14,
                                        Gallop = 14,
                                        Trot = 14,
                                        Jumping = 14 },
                new CustomizationBonus { Name = "Iriksen väritys, sateenkaari",
                                        Stamina = 8,
                                        Speed = 8,
                                        Dressage = 8,
                                        Gallop = 8,
                                        Trot = 8,
                                        Jumping = 8 },
                new CustomizationBonus { Name = "Iriksen väritys, muut värit",
                                        Stamina = 5,
                                        Speed = 5,
                                        Dressage = 5,
                                        Gallop = 5,
                                        Trot = 5,
                                        Jumping = 5 },
                new CustomizationBonus { Name = "Sykeröletitys",
                                        Stamina = 2,
                                        Speed = 2,
                                        Dressage = 2,
                                        Gallop = 2,
                                        Trot = 2,
                                        Jumping = 2 },
                new CustomizationBonus { Name = "Hännän letitys",
                                        Stamina = 2,
                                        Speed = 2,
                                        Dressage = 2,
                                        Gallop = 2,
                                        Trot = 2,
                                        Jumping = 2 },
                new CustomizationBonus { Name = "Klippaustyyli",
                                        Stamina = 2,
                                        Speed = 2,
                                        Dressage = 2,
                                        Gallop = 2,
                                        Trot = 2,
                                        Jumping = 2 },

             }.ToArray();

        }
    }
}
